---
version: "3"

vars:
  SECRETS_ENCRYPTED_PATH: encrypted/secrets.tar.gz.enc
  SECRETS_PATHS: |
    ./secrets \

env:
  SOPS_AGE_KEY_FILE:
    sh: echo $HOME/.config/sops/age/tonychg.txt

tasks:
  encrypt:
    desc: Encrypt secrets
    silent: true
    cmds:
      - |
        tar -cvzf - \
          {{.SECRETS_PATHS}} \
          | sops --encrypt /dev/stdin > {{.SECRETS_ENCRYPTED_PATH}}
  decrypt:
    desc: Decrypt secrets
    silent: true
    cmds:
      - |
        sops --decrypt {{.SECRETS_ENCRYPTED_PATH}} | tar -C . -xzvf -
  backup:
    cmds:
      - echo "Hello, world!"
